[2022-07-11 17:39:32,242: INFO: stage_01_get_data]: 
********************
[2022-07-11 17:39:32,242: INFO: stage_01_get_data]: >>>>> stage get_data started <<<<<
[2022-07-11 17:39:32,242: ERROR: stage_01_get_data]: name 'main' is not defined
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 41, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
NameError: name 'main' is not defined
[2022-07-11 17:49:42,666: INFO: stage_01_get_data]: 
********************
[2022-07-11 17:49:42,666: INFO: stage_01_get_data]: >>>>> stage get_data started <<<<<
[2022-07-11 17:49:42,668: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-07-11 17:49:42,668: INFO: common]: yaml file: params.yaml loaded successfully
[2022-07-11 17:49:42,680: INFO: common]: created directory at: data/cat
[2022-07-11 17:49:42,681: ERROR: stage_01_get_data]: [WinError 3] The system cannot find the path specified: '../outside_data/cat'
Traceback (most recent call last):
  File "src/stage_01_get_data.py", line 41, in <module>
    get_data(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_get_data.py", line 29, in get_data
    copy_files(source_download_dir, local_data_dir)
  File "d:\work\tensorflow_dvc\src\utils\common.py", line 21, in copy_files
    list_of_files = os.listdir(source_download_dir)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '../outside_data/cat'
